### PR TITLE
Rename Rxy to Rphi

### PR DESCRIPTION
**Pull request by perlinm**

### CODE REVIEW

**Review by vtomole — APPROVED** [review]
LGTM. Thanks for the small doc cleanups as well!

**Comment by richrines1** [comment]
what do you think about using `phi` instead of `axis_angle` now? I kind of prefer the more descriptive name but it feels especially weird to use "phi" in the name of we call the variable something else

**Comment by perlinm** [comment]
> what do you think about using `phi` instead of `axis_angle` now? I kind of prefer the more descriptive name but it feels especially weird to use "phi" in the name of we call the variable something else

Hmm, this makes sense I suppose.  Should I also rename `rot_angle` to `theta`?

**Comment by richrines1** [comment]
> Should I also rename `rot_angle` to `theta`?

yeah I guess that would be consistent (and also consistent w/ `FermionicSWAPGate`)

**Comment by perlinm** [comment]
Alright done @richrines1

**Review by richrines1 — APPROVED** [review]
cool lgtm

**Pull request merged**
