### PR TITLE
Make `api_key` first argument in `css.Service` class

### PR DESCRIPTION
**Pull request by pgoiporia**
Addresses #261

### CODE REVIEW

**Comment by pgoiporia** [comment]
> Can you merge this branch into the notebook tests pr? I want to see if things still pass.

Will do. Gonna squash some notebook test bugs first

**Review by vtomole — DISMISSED** [review]
LGTM

**Comment by pgoiporia** [comment]
Merging these changes into #249

**Comment by vtomole** [comment]
@PalashGoiporia Let's just merge this into `main`. The other PR is a decent size already.

**Comment by pgoiporia** [comment]
> @PalashGoiporia Let's just merge this into `main`. The other PR is a decent size already.

Sounds good

**Review by singular-value — APPROVED** [review]
lgtm

**Pull request merged**
