### PR TITLE
Daily integration test for setting CQ token

### PR DESCRIPTION
**Pull request by teaguetomesh**
Daily integration test for setting a CQ token. Related to PRs in:
- `general-superstaq` [PR236](https://github.com/SupertechLabs/general-superstaq/pull/236)
- `superstaq` [PR2051](https://github.com/SupertechLabs/SuperstaQ/pull/2051)

### CODE REVIEW

**Comment by teaguetomesh** [comment]
Tested locally -- checks should pass once [PR236](https://github.com/SupertechLabs/general-superstaq/pull/236) is merged.

**Review by knsmith — APPROVED** [review]
LGTM

**Review by knsmith — CHANGES_REQUESTED** [review]
Actually there's a test failing that needs to be looked at....

**Comment by richrines1** [comment]
@teaguetomesh setting to draft - do you mind migrating this branch to https://github.com/SupertechLabs/client-superstaq and opening a pr there (and then closing this one)? (lmk if you have trouble migrating)

**Pull request closed without merging**
