### PR TITLE
Revert "Added check for an `ibmq_token` (#133)"

### PR DESCRIPTION
**Pull request by dowusu-antwi**
This reverts commit ea7da561afd9e06ba9e1cc7d425c411efb38c359.

### CODE REVIEW

**Comment by vtomole** [comment]
Why?

**Comment by dowusu-antwi** [comment]
> Why?

IBM Q authentication is being addressed in recent changes to SuperstaQ -- once those are reviewed, they will obviate these changes. We can hold off until those changes are approved.

**Comment by vtomole** [comment]
👍

**Review by singular-value — APPROVED** [review]
👍

**Pull request merged**
