### PR TITLE
"Emit `num_copies` in` ParallelRGate`s QASM

### PR DESCRIPTION
**Pull request by vtomole**

### CODE REVIEW

**Comment by vtomole** [comment]
Omg. the `num_copies` is first in QASM. hold on.

**Comment by richrines1** [comment]
why this change? the qasm string for qiskit's `GR` gate doesn't include a `num_copies` parameter so to be consistent this shouldn't either imo

**Comment by vtomole** [comment]
Oh, right.

**Comment by vtomole** [comment]
Closing.

**Pull request closed without merging**
