### PR TITLE
Generalize `_version_test`

### PR DESCRIPTION
**Pull request by vtomole**
This makes it so you don't need to update version test when updating the version.

### CODE REVIEW

**Review by richrines1 — APPROVED** [review]
lgtm. assuming this will be replicated in the other repos?

**Comment by vtomole** [comment]
> assuming this will be replicated in the other repos?


Very weird that `import packaging` doesn't work in other repos. I have to do `import packaging.version`. Will look into it this evening.

**Comment by richrines1** [comment]
> Very weird that `import packaging` doesn't work in other repos. I have to do `import packaging.version`. Will look into it this evening.

`packaging.__init__` doesn't import any submodules itself, so `packaging.version` should always need to be explicitly imported somewhere. i think it works in css because `cirq` imports `matplotlib`, and `matplotlib.__init__` already imports stuff from `packaging.version`. (imo for consistency we should use `import packaging.version` here too though)

**Review by stephanielee9 — APPROVED** [review]
lgtm - should we eventually implement a version test in supermarq as well?

**Comment by vtomole** [comment]
> should we eventually implement a version test in supermarq as well?

Yes. Done: https://github.com/SupertechLabs/SupermarQ/pull/48

**Pull request merged**
