### PR TITLE
Remove Cirq upper bound requirement 

### PR DESCRIPTION
**Pull request by perlinm**

### CODE REVIEW

**Review by vtomole — APPROVED** [review]

**Comment by vtomole** [comment]
Ready for review.

**Comment by richrines1** [comment]
I think we need to update the lower bound as well - e.g. 0.11 is broken due to `Circuit.all_measurement_key_names` and `cirq.ParallelGate`

**Comment by vtomole** [comment]
I think we should do `cirq>=$thelatestversion` from now on. In this case `cirq>=0.13.0`. 
Thoughts?

**Comment by richrines1** [comment]
> I think we should do cirq>=$thelatestversion from now on. In this case cirq>=0.13.0.
Thoughts?

in general I think it's best to keep the requirements loose whenever possible and only update lower bounds when we have a reason to, so as to avoid unnecessarily creating dependency issues for someone updating cirq-superstaq. That said, I think there are pretty good reasons to require `>=0.13` at this point

**Comment by richrines1** [comment]
lgtm, leaving for others

**Review by dowusu-antwi — APPROVED** [review]
LGTM.

I'm sympathetic to Rich's comments -- it makes sense to be as loose as possible with requirements. But yeah, in this particular case might as well require `>=0.13`.

**Pull request merged**
