### PR TITLE
Support testing with qtrl

### PR DESCRIPTION
**Pull request by richrines1**
changes required to fix testing and test coverage when qtrl is available in the local environement:
* include "state_jp" and "pulse_list_jp" elements in json_dict passed to `aqt.read_json()` in all tests (aqt_test.py and service_test.py)
* mock qtrl unavailability in `aqt_test.test_read_json()` so that it always functions as if qtrl is not installed
* add `aqt_test.test_read_json_with_qtrl()` to check qtrl functionality (skipped when qtrl is not available)

### CODE REVIEW

**Review by vtomole — COMMENTED** [review]
As a test, can you temporarily remove qtrl from `requirements.txt` and see if the checks pass?

**Review by vtomole — APPROVED** [review]
LGTM

**Comment by singular-value** [comment]
lgtm and +1 to @vtomole's suggestion:
> As a test, can you temporarily remove qtrl from dev-requirements.txt and see if the checks pass?

**Comment by vtomole** [comment]
@singular-value That comment was mistaken. There is no qtrl in `dev-requirements.txt`.

**Comment by singular-value** [comment]
> @singular-value That comment was mistaken. There is no qtrl in `dev-requirements.txt`.

👍

**Pull request merged**
