### PR TITLE
Add client-side functionality for setting IBMQ token

### PR DESCRIPTION
**Pull request by dowusu-antwi**
Lets `css` work with `PostIBMQToken` endpoint.

### CODE REVIEW

**Comment by dowusu-antwi** [comment]
Appear to also be some errors with the way we're looking at the JSON storing the input token... looking into now.
client-set-error

**Comment by richrines1** [comment]
shouldn't `ibmq_set_token()` already be inherited from `UserConfig`?

**Comment by dowusu-antwi** [comment]
> shouldn't `ibmq_set_token()` already be inherited from `UserConfig`?

Yes -- I see now how it matches our use of `aqt_upload_configs`, also inherited from 'UserConfig'. Fixed.

**Comment by dowusu-antwi** [comment]
Requesting re-review. `JSONDecodeError` fixed on SuperstaQ:

flask-fixes

**Comment by dowusu-antwi** [comment]
Requesting re-review @richrines1 @vtomole.

**Review by vtomole — APPROVED** [review]
LGTM

**Pull request merged**
